### ISSUE TITLE
doesn't work with streams3

### ISSUE THREAD

**Issue by contra** [armed/ordered-read-streams#10]
will add more info as i continue to debug, but it appears that this doesn't work with through2 2.0 which is streams3 but it does with with through2 0.x which is streams2

**Comment by armed** [comment]
Hi, @contra currently tests are written using through2 2.x.x. Is issue occurs in latest version of ordered-read-streams?

**Comment by phated** [comment]
@contra any more information for this?  The versions it uses seem to indicate it works with Streams3.  I'd like to get this bumped to 1.0

**Comment by contra** [comment]
Something must have updated, seems to work fine now
