### ISSUE TITLE
Write after end

### ISSUE THREAD

**Issue by phated** [armed/ordered-read-streams#13]
Hey @armed!  I'm working on some more gulpjs/glob-stream stuff and I ran into a problem when using `ordered-read-streams` with the `pumpify` module which wraps it in a DuplexStream.  It seems that if I use `ordered-read-streams` twice, as separate segments of a pipeline, it causes a "write after end" error.  

I've been told this is due to putting a Readable stream in the middle of the pipeline (as the first argument to `pumpify`).

I think I have this issue solved by making `ordered-read-streams` inherit from `Duplex` instead of `Readable` but I'm still working out the details of backpressure.  I hope to have a PR submitted soon.

Do you have any thoughts about this?

This is the simplified example of what I'm experiencing:

```js
var Combine = require('ordered-read-streams');
var pumpify = require('pumpify');
var miss = require('mississippi');

function double() {
  return miss.through.obj(function(num, _, cb) {
    cb(null, num * 2);
  });
}

var stream1 = pumpify.obj(Combine([
  miss.from.obj([1,2,3]), miss.from.obj([4,5,6])
]), double());

var stream2 = pumpify.obj(Combine([
  miss.from.obj([10,11,12]), miss.from.obj([20,21,22])
]), double());

function log(results) {
  console.log(results);
}
                      
stream1.pipe(stream2).pipe(miss.concat(log));
```

**Comment by armed** [comment]
Hey, @phated 

You now can push to this repository. Feel like home :)

**Comment by phated** [comment]
It seems like there's no need to change this - ref https://github.com/armed/ordered-read-streams/pull/14#issuecomment-277083776
