### ISSUE TITLE
Need to rewrite tests

### ISSUE THREAD

**Issue by phated** [armed/ordered-read-streams#15]
I was using the implementation of this library as my basis for https://github.com/gulpjs/to-through and found that it isn't using `on('readable')` properly.  This isn't apparent because the tests are using `on('data')` which is putting things into flowing mode (I think).  I'll have to rewrite the tests to use `from2` and other stream utilities. 

Reference material: http://codewinds.com/blog/2013-08-04-nodejs-readable-streams.html

**Comment by armed** [comment]
Hey, @phated

Thanks for letting me know. Feel free to do what you think is necessary.

**Comment by phated** [comment]
👍  I just created this so I could keep track of it.

**Comment by phated** [comment]
Fixed by 7e179d797d0b444ee7e6fa7977f37f414d9995d7

@armed can you add me to the project on npm?  Once you do, I'll cut a release.

**Comment by armed** [comment]
Hey, @phated 

Just executed `npm owner add phated ordered-read-streams`. Not sure is this what you asked for.
