### ISSUE TITLE
Transform stream

### ISSUE THREAD

**Issue by piranna** [armed/ordered-read-streams#17]
Allow to use `ordered-read-streams` as a Transform stream, accepting as input a stream-of-streams when no input array is given. This could be combined with the current behaviour by pipeing itself a Readable stream with the content of the input array in case it's given, or by appending the incoming streams to the array.

**Comment by phated** [comment]
Just use my `to-through` module. This is the wrong abstraction layer for what you want.

**Comment by piranna** [comment]
Could you put a link to the repo?

**Comment by phated** [comment]
https://github.com/gulpjs/to-through

**Comment by piranna** [comment]
> https://github.com/gulpjs/to-through

Interesting module :-) But it's not related to what I'm talking about here, because it allow stream more content. What I'm asking for is to be able to define the streams list by using an input stream-of-streams instead of just only by using an array-of-streams. This would allow for example to add more input streams on the fly. I could be able to do a quick pull-requests for that to show it if needed.

**Comment by piranna** [comment]
Could you be able to re-open the issue?

**Comment by phated** [comment]
@piranna I'd prefer to mirror the API for duplexify/pumpify for that functionality (add a method for setting or adding source files) - see https://github.com/mafintosh/duplexify

**Comment by phated** [comment]
Opened a new issue for that API
